[package]
name = "passwords"
version = "0.0.0"
description = "Passwords"
authors = ["Toshiki"]
license = "MIT"
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
# https://crates.io
tauri = { version = "1.5.4", features = [ "http-all", "shell-open"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
env_logger = "0.10.1"
log = "0.4.20"
rand = "0.8.5"
chrono = "0.4.31"
toml = "0.8.8"
uuid = { version = "1.6.1", features = ["v7","fast-rng","macro-diagnostics"] }
diesel = { version = "2.1.4", features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = { version = "2.1.0", features = ["sqlite"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
