[package]
authors = ["Toshiki"]
description = "Passwords"
edition = "2021"
license = "MIT"
name = "passwords"
repository = ""
version = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = {version = "1.5.1", features = []}# features = ["codegen", "config-json5", "config-toml", "isolation", "quote", "tauri-codegen"]

[dependencies]
# https://crates.io
chrono = "0.4.31"
diesel = {version = "2.1.4", features = ["sqlite", "r2d2", "chrono"]}
diesel_migrations = {version = "2.1.0", features = ["sqlite"]}
env_logger = "0.10.1"
log = "0.4.20"
rand = "0.8.5"
serde = {version = "1.0.195", features = ["derive"]}
serde_json = "1.0.111"
tauri = {version = "1.5.4", features = ["http-all", "shell-open"]}
toml = "0.8.8"
uuid = {version = "1.6.1", features = ["v7", "fast-rng", "macro-diagnostics"]}

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
