[package]
name = "sns-tools"
version = "0.0.0"
description = "SNS Tools"
authors = ["Toshiki"]
license = "MIT"
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
# https://crates.io/crates/tauri
tauri = { version = "1.5", features = [ "http-all", "shell-open"] }

# https://crates.io/crates/serde
serde = { version = "1.0", features = ["derive"] }

# https://crates.io/crates/serde_json
serde_json = "1.0"

# https://crates.io/crates/reqwest
reqwest = { version = "0.11", features = ["json"] }

# https://crates.io/crates/rspc
# https://www.rspc.dev
rspc = { version = "0.1", features = ["tauri"] }

# https://crates.io/crates/tokio
tokio = { version = "1", features = ["full"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
