/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "x.getAppName", input: never, result: string } | 
        { key: "x.getAppName2", input: string, result: string },
    mutations: never,
    subscriptions: never
};
