[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
address = "127.0.0.1"
port = 1420
open = false

[[hooks]]
stage = "build"
command = "tailwindcss"
command_arguments = ["-c", "./tailwind.config.js", "-o", "./tailwind.css", "--minify"]
